version: "3"

services:
  postgres-db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB="london_bike"
    volumes:
      - "./london_bike_data:/var/lib/postgresql/data"
    ports:
      - ${DOCKER_POSTGRES_PORT}
  postgres-Admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASS}
    ports:
      - ${DOCKER_PGADMIN_PORT}
