version: '3.3'

services:
    db:
      image: postgres:13
      restart: always
      env_file:
        - .env
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASS}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - ${DOCKER_POSTGRES_PORT}
      volumes:
        - "../Extracting_data/london_bike_data:/var/lib/postgresql/data"
      networks:
        - postgres-network
    postgres-Admin:
      image: dpage/pgadmin4
      env_file:
        - .env
      environment: 
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASS}
      ports:
        - ${DOCKER_PGADMIN_PORT}
      networks:
        - postgres-network

    metabase:
      volumes:
        - ./metabase-data:/metabase-data
      env_file:
        - .env
      environment:
        - MB_DB_FILE=/metabase-data/metabase.db
        - MB_DB_TYPE=postgres
        - MB_DB_DBNAME=${POSTGRES_DB}
        - MB_DB_PORT=5432
        - MB_DB_USER=${POSTGRES_USER}
        - MB_DB_PASS=${POSTGRES_PASS}
        - MB_DB_HOST=db
      ports:
        - 3000:3000
      image: metabase/metabase
      restart: always
      depends_on: 
        - db
      networks:
        - postgres-network
networks:
  postgres-network:
    driver: bridge